name: wallpaper_app
description: "Wallpaper app using Pexels API"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"  # Ensures compatibility with super-parameters and null safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  flutter_wallpaper_manager: ^0.0.4
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.2
  flutter_image_compress: ^2.1.0
  workmanager: ^0.5.2
  universal_html: ^2.2.4
  
 
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  # assets:
  #   - assets/logo.png
  #   - assets/chip.png
